###查询课程信息
POST {{content_host}}/content/course/list?pageNo=1&pageSize=2
Content-Type: application/json

{
  "auditStatus": "202004",
  "courseName": "java",
  "publishStatus": ""
}

### 课程分类信息查询测试接口
GET {{content_host}}/content/course-category/tree-nodes


### 创建课程
POST {{content_host}}/content/course
Content-Type: application/json

{
  "charge": "202001",
  "price": 0,
  "originalPrice":0,
  "qq": "22333",
  "wechat": "223344",
  "phone": "13333333",
  "validDays": 365,
  "mt": "1-1",
  "st": "1-1-1",
  "name": "test",
  "pic": "",
  "teachmode": "200002",
  "users": "1，1，2，41111111111111111111111111111111111111111111111",
  "tags": "",
  "grade": "204001",
  "description": ""
}


### 查询课程信息
GET {{content_host}}/content/course/1

### 根据课程id查询课程信息
GET {{content_host}}/content/course/40
Content-Type: application/json

### 修改课程
PUT {{content_host}}/content/course
Content-Type: application/json

### 修改课程
PUT {{content_host}}/content/course
Content-Type: application/json

{
  "id": 40,
  "name": "SpringBoot核心",
  "users": "Spring Boot初学者",
  "tags": "Spring项目的快速构建",
  "mt": "1-3",
  "st": "1-3-2",
  "grade": "200003",
  "teachmode": "201001",
  "description": "222课程系统性地深度探讨 Spring Boot 核心特性，引导小伙伴对 Java 规范的重视，启发对技术原理性的思考，掌握排查问题的技能，以及学习阅读源码的方法和技巧，全面提升研发能力，进军架构师队伍。",
  "pic": "https://cdn.educba.com/academy/wp-content/uploads/2018/08/Spring-BOOT-Interview-questions.jpg",
  "charge": "201001",
  "price": 1000
}

### 查询某个课程的课程计划

GET {{content_host}}/content/teachplan/117/tree-nodes



### 新增课程计划--章
POST {{content_host}}/content/teachplan
Content-Type: application/json

{
  "courseId" : 74,
  "parentid": 0,
  "grade" : 1,
  "pname" : "新章名称 [点击修改]"
}

### 新增课程计划--节,从数据库找到第一级的课程计划id向其下边添加计划
POST {{content_host}}/content/teachplan
Content-Type: application/json

{
  "courseId" : 74,
  "parentid": 247,
  "grade" : 2,
  "pname" : "小节名称 [点击修改]"
}


### 课程课程计划,需要从数据库找到修改的课程计划id
POST {{content_host}}/content/teachplan
Content-Type: application/json

{
  "changeDate" : null,
  "courseId" : 22,
  "cousePubId" : null,
  "createDate" : null,
  "ctlBarShow" : false,
  "ctlEditTitle" : true,
  "endTime" : null,
  "grade" : "2",
  "isPreview" : "1",
  "mediaType" : "",
  "orderby" : 1,
  "parentid" : 237,
  "pname" : "第1节修改名称",
  "startTime" : null,
  "status" : null,
  "teachPlanId" : 240
}


### 删除课程计划
DELETE {{content_host}}/content/teachplan/21


### docker启动nacos命令
docker run -d \
--name nacos \
-p 8848:8848  -p 9848:9848 -p 9849:9849 \
--privileged=true \
-v /docker-data/nacos/logs/:/home/nacos/logs \
-v /docker-data/nacos/conf/:/home/nacos/conf \
nacos/nacos-server




### 课程查询列表
POST {{gateway_host}}/content/course/list?pageNo=2&pageSize=1
Content-Type: application/json

{
  "auditStatus": "202002",
  "courseName": ""
}

### docker安装minio命令
docker run -p 9000:9000 -p 9090:9090 \
--net=host \
--name minio \
-d --restart=always \
-e "MINIO_ACCESS_KEY=minioadmin" \
-e "MINIO_SECRET_KEY=minioadmin" \
-v /docker-data/minio/data:/data \
-v /docker-data/minio/config:/root/.minio \
minio/minio server \
/data --console-address ":9090" -address ":9000"


### 上传文件
POST {{media_host}}/media/upload/coursefile
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="filedata"; filename="1.jpg"
Content-Type: application/octet-stream

< C:\Users\杜展鹏\Pictures\Camera Roll\wallhaven-vq9jgm.jpg



### 根据课程id查询对应教师的基本信息
GET {{gateway_host}}/content/courseTeacher/list/72


### 查询全部的媒资列表
POST {{gateway_host}}/media/files?pageNo=1&pageSize=10


docker run  -p 8088:8088 \
-d --name=xxl-job-admin --restart=always \
-v /docker-data/xxl-job/data/applogs/application.properties:/application.properties \
-v /docker-data/xxl-job/data/applogs/logs:/data/applogs \
-e PARAMS='--spring.config.location=/application.properties' xuxueli/xxl-job-admin:2.3.1


### 课程计划绑定视频
POST {{media_host}}/media/teachplan/association/media
Content-Type: application/json

{
  "mediaId": "",
  "fileName": "",
  "teachplanId": ""
}


### docker安装nginx
docker run -p 80:80 \
--name nginx \
-v /docker-data/nginx/conf/nginx.conf:/etc/nginx/nginx.conf \
-v /docker-data/nginx/conf/conf.d:/etc/nginx/conf.d \
-v /docker-data/nginx/log:/var/log/nginx \
-v /docker-data/nginx/html:/usr/share/nginx/html \
-d nginx:latest


docker cp nginx:/etc/nginx/nginx.conf /docker-data/nginx/conf/nginx.conf

docker cp nginx:/etc/nginx/conf.d /docker-data/nginx/conf/conf.d

docker cp nginx:/usr/share/nginx/html /docker-data/nginx/


### 课程发布
POST {{content_host}}/content/coursepublish/2
